import { getDb } from '../src/config/database.js';
import { services } from '../src/db/schema/services.js';

const SEED_SERVICES = [
  // Exchanges
  {
    id: 'binance',
    name: 'Binance',
    slug: 'binance',
    category: 'exchange',
    website: 'https://binance.com',
    description: 'World\'s largest cryptocurrency exchange by trading volume',
    foundedYear: 2017,
    headquarters: 'Cayman Islands',
    legalEntity: 'Binance Holdings Ltd',
    tags: JSON.stringify(['cex', 'global', 'derivatives']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    slug: 'coinbase',
    category: 'exchange',
    website: 'https://coinbase.com',
    description: 'US-based regulated cryptocurrency exchange',
    foundedYear: 2012,
    headquarters: 'San Francisco, USA',
    legalEntity: 'Coinbase Global Inc',
    tags: JSON.stringify(['cex', 'regulated', 'public-company']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'kraken',
    name: 'Kraken',
    slug: 'kraken',
    category: 'exchange',
    website: 'https://kraken.com',
    description: 'Cryptocurrency exchange with advanced trading features',
    foundedYear: 2011,
    headquarters: 'San Francisco, USA',
    legalEntity: 'Payward Inc',
    tags: JSON.stringify(['cex', 'regulated', 'derivatives']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'bybit',
    name: 'Bybit',
    slug: 'bybit',
    category: 'exchange',
    website: 'https://bybit.com',
    description: 'Cryptocurrency derivatives exchange',
    foundedYear: 2018,
    headquarters: 'Dubai, UAE',
    legalEntity: 'Bybit Fintech Ltd',
    tags: JSON.stringify(['cex', 'derivatives', 'global']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'okx',
    name: 'OKX',
    slug: 'okx',
    category: 'exchange',
    website: 'https://okx.com',
    description: 'Global cryptocurrency exchange and Web3 ecosystem',
    foundedYear: 2017,
    headquarters: 'Seychelles',
    legalEntity: 'OKX Holdings Ltd',
    tags: JSON.stringify(['cex', 'web3', 'global']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'bitfinex',
    name: 'Bitfinex',
    slug: 'bitfinex',
    category: 'exchange',
    website: 'https://bitfinex.com',
    description: 'Cryptocurrency exchange known for advanced trading',
    foundedYear: 2012,
    headquarters: 'Hong Kong',
    legalEntity: 'iFinex Inc',
    tags: JSON.stringify(['cex', 'advanced', 'global']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'gate-io',
    name: 'Gate.io',
    slug: 'gate-io',
    category: 'exchange',
    website: 'https://gate.io',
    description: 'Global cryptocurrency exchange with wide token selection',
    foundedYear: 2013,
    headquarters: 'Cayman Islands',
    legalEntity: 'Gate Technology Inc',
    tags: JSON.stringify(['cex', 'global', 'altcoins']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'kucoin',
    name: 'KuCoin',
    slug: 'kucoin',
    category: 'exchange',
    website: 'https://kucoin.com',
    description: 'Global cryptocurrency exchange',
    foundedYear: 2017,
    headquarters: 'Seychelles',
    legalEntity: 'Mek Global Ltd',
    tags: JSON.stringify(['cex', 'global', 'altcoins']),
    addresses: JSON.stringify({}),
  },
  // Wallets
  {
    id: 'metamask',
    name: 'MetaMask',
    slug: 'metamask',
    category: 'wallet',
    website: 'https://metamask.io',
    description: 'Leading self-custody crypto wallet',
    foundedYear: 2016,
    legalEntity: 'Consensys AG',
    tags: JSON.stringify(['wallet', 'web3', 'defi']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'phantom',
    name: 'Phantom',
    slug: 'phantom',
    category: 'wallet',
    website: 'https://phantom.app',
    description: 'Multi-chain wallet for Solana, Ethereum, and Bitcoin',
    foundedYear: 2021,
    legalEntity: 'Phantom Technologies Inc',
    tags: JSON.stringify(['wallet', 'solana', 'web3']),
    addresses: JSON.stringify({}),
  },
  // Hardware wallets
  {
    id: 'ledger',
    name: 'Ledger',
    slug: 'ledger',
    category: 'hardware_wallet',
    website: 'https://ledger.com',
    description: 'Hardware wallet manufacturer for secure crypto storage',
    foundedYear: 2014,
    headquarters: 'Paris, France',
    legalEntity: 'Ledger SAS',
    tags: JSON.stringify(['hardware', 'security', 'self-custody']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'trezor',
    name: 'Trezor',
    slug: 'trezor',
    category: 'hardware_wallet',
    website: 'https://trezor.io',
    description: 'Original hardware wallet manufacturer',
    foundedYear: 2013,
    headquarters: 'Prague, Czech Republic',
    legalEntity: 'SatoshiLabs s.r.o.',
    tags: JSON.stringify(['hardware', 'security', 'self-custody', 'open-source']),
    addresses: JSON.stringify({}),
  },
  // DeFi
  {
    id: 'lido',
    name: 'Lido',
    slug: 'lido',
    category: 'defi',
    website: 'https://lido.fi',
    description: 'Liquid staking protocol for Ethereum',
    foundedYear: 2020,
    tags: JSON.stringify(['defi', 'staking', 'ethereum']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'aave',
    name: 'Aave',
    slug: 'aave',
    category: 'defi',
    website: 'https://aave.com',
    description: 'Open source decentralized lending protocol',
    foundedYear: 2020,
    tags: JSON.stringify(['defi', 'lending', 'governance']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'uniswap',
    name: 'Uniswap',
    slug: 'uniswap',
    category: 'defi',
    website: 'https://uniswap.org',
    description: 'Decentralized exchange protocol on Ethereum',
    foundedYear: 2018,
    tags: JSON.stringify(['defi', 'dex', 'ethereum']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'makerdao',
    name: 'MakerDAO',
    slug: 'makerdao',
    category: 'defi',
    website: 'https://makerdao.com',
    description: 'Decentralized stablecoin (DAI) protocol',
    foundedYear: 2017,
    tags: JSON.stringify(['defi', 'stablecoin', 'governance']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'compound',
    name: 'Compound',
    slug: 'compound',
    category: 'defi',
    website: 'https://compound.finance',
    description: 'Decentralized lending and borrowing protocol',
    foundedYear: 2018,
    tags: JSON.stringify(['defi', 'lending', 'governance']),
    addresses: JSON.stringify({}),
  },
  // Bridges
  {
    id: 'stargate',
    name: 'Stargate',
    slug: 'stargate',
    category: 'bridge',
    website: 'https://stargate.finance',
    description: 'Cross-chain bridge protocol',
    foundedYear: 2022,
    tags: JSON.stringify(['bridge', 'cross-chain', 'defi']),
    addresses: JSON.stringify({}),
  },
  // Custodians
  {
    id: 'bitgo',
    name: 'BitGo',
    slug: 'bitgo',
    category: 'custodian',
    website: 'https://bitgo.com',
    description: 'Institutional digital asset custody',
    foundedYear: 2013,
    headquarters: 'Palo Alto, USA',
    legalEntity: 'BitGo Inc',
    tags: JSON.stringify(['custody', 'institutional', 'qualified-custodian']),
    addresses: JSON.stringify({}),
  },
  {
    id: 'fireblocks',
    name: 'Fireblocks',
    slug: 'fireblocks',
    category: 'custodian',
    website: 'https://fireblocks.com',
    description: 'Enterprise digital asset custody and operations',
    foundedYear: 2018,
    headquarters: 'New York, USA',
    legalEntity: 'Fireblocks Inc',
    tags: JSON.stringify(['custody', 'institutional', 'enterprise']),
    addresses: JSON.stringify({}),
  },
];

async function seed() {
  console.log('Seeding database (services only — no fake scores)...');

  const db = getDb();

  for (const service of SEED_SERVICES) {
    await db
      .insert(services)
      .values({
        ...service,
        isActive: true,
        isUnderReview: false,
      })
      .onConflictDoNothing();
  }

  console.log(`Inserted ${SEED_SERVICES.length} services`);
  console.log('Seed complete! Scores will be computed by the scoring pipeline.');
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
